name: Publish Testing Images to Local Registry
on:
  push:
    tags:
      - "v*.*.*-test" # Matches tags like v1.2.3-test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and Push Docker image
        run: |
          # Build and push the image as latest
          docker build -t dcr.int.daneskalski.com/daneski13/docker-smtexas:latest-test .
          docker push dcr.int.daneskalski.com/daneski13/docker-smtexas:latest-test
